import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  PageBreak,
  Header,
  Footer,
  BorderStyle,
} from "docx";

interface DocSection {
  name: string;
  content: string;
}

export async function createDocumentDOCX(
  documents: DocSection[],
  businessName: string
): Promise<Buffer> {
  const date = new Date().toLocaleDateString("en-US", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  // Build sections: cover page + TOC + each document
  const children: Paragraph[] = [];

  // Cover page
  children.push(
    new Paragraph({ spacing: { before: 4000 } }),
    new Paragraph({
      children: [
        new TextRun({
          text: "DocketPack",
          bold: true,
          size: 56,
          font: "Georgia",
        }),
      ],
    }),
    new Paragraph({ spacing: { before: 400 } }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Document Pack for`,
          size: 28,
          font: "Georgia",
          color: "666666",
        }),
      ],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: businessName,
          bold: true,
          size: 40,
          font: "Georgia",
        }),
      ],
    }),
    new Paragraph({ spacing: { before: 600 } }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated: ${date}`,
          size: 20,
          color: "666666",
        }),
      ],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `${documents.length} documents included`,
          size: 20,
          color: "666666",
        }),
      ],
    }),
    new Paragraph({ spacing: { before: 4000 } }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Documents generated by AI. Review with a qualified professional before use.",
          size: 16,
          italics: true,
          color: "999999",
        }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] })
  );

  // Table of contents
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Contents",
          bold: true,
          size: 36,
          font: "Georgia",
        }),
      ],
    }),
    new Paragraph({ spacing: { before: 400 } })
  );

  documents.forEach((doc, i) => {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${i + 1}. ${doc.name}`,
            size: 22,
          }),
        ],
        spacing: { after: 100 },
      })
    );
  });

  children.push(new Paragraph({ children: [new PageBreak()] }));

  // Each document section
  documents.forEach((doc) => {
    // Document title
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: doc.name,
            bold: true,
            size: 32,
            font: "Georgia",
          }),
        ],
        spacing: { after: 100 },
        border: {
          bottom: {
            color: "333333",
            space: 4,
            style: BorderStyle.SINGLE,
            size: 6,
          },
        },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Prepared for ${businessName}`,
            size: 18,
            italics: true,
            color: "666666",
          }),
        ],
        spacing: { after: 300 },
      })
    );

    // Split content into paragraphs
    const lines = doc.content.split("\n").filter((l) => l.trim());
    for (const line of lines) {
      const trimmed = line.trim();

      // Detect headings (markdown headers or numbered sections)
      if (
        trimmed.match(/^#{1,3}\s/) ||
        trimmed.match(/^\d+\.\s+[A-Z]/)
      ) {
        const cleanText = trimmed.replace(/^#{1,3}\s*/, "");
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: cleanText,
                bold: true,
                size: 24,
                font: "Georgia",
              }),
            ],
            spacing: { before: 300, after: 100 },
          })
        );
      } else if (trimmed.startsWith("- ") || trimmed.startsWith("• ")) {
        // Bullet points
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: trimmed.replace(/^[-•]\s*/, ""),
                size: 22,
              }),
            ],
            bullet: { level: 0 },
            spacing: { after: 40 },
          })
        );
      } else {
        // Regular paragraph
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: trimmed,
                size: 22,
              }),
            ],
            spacing: { after: 120 },
          })
        );
      }
    }

    // Page break between docs
    children.push(new Paragraph({ children: [new PageBreak()] }));
  });

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440,
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: `DocketPack — ${businessName}`,
                    size: 16,
                    color: "999999",
                  }),
                ],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "Generated by DocketPack — Review with a qualified professional before use",
                    size: 14,
                    color: "999999",
                  }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
