import { jsPDF } from "jspdf";

interface DocSection {
  name: string;
  content: string;
}

export function createDocumentPDF(
  documents: DocSection[],
  businessName: string
): ArrayBuffer {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Cover page
  pdf.setFontSize(32);
  pdf.text("DocketPack", margin, 60);
  pdf.setFontSize(16);
  pdf.text(`Document Pack for`, margin, 80);
  pdf.setFontSize(24);
  pdf.text(businessName, margin, 95);
  pdf.setFontSize(10);
  pdf.text(
    `Generated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`,
    margin,
    115
  );
  pdf.text(`${documents.length} documents included`, margin, 125);
  pdf.setFontSize(8);
  pdf.text(
    "Documents generated by AI. Review with a qualified professional before use.",
    margin,
    270
  );

  // Table of contents
  pdf.addPage();
  pdf.setFontSize(20);
  pdf.text("Contents", margin, 30);
  pdf.setFontSize(10);
  let tocY = 50;
  documents.forEach((doc, i) => {
    if (tocY > 270) {
      pdf.addPage();
      tocY = 30;
    }
    pdf.text(`${i + 1}. ${doc.name}`, margin, tocY);
    tocY += 8;
  });

  // Document sections
  documents.forEach((doc) => {
    pdf.addPage();
    pdf.setFontSize(18);
    pdf.text(doc.name, margin, 30);
    pdf.setFontSize(8);
    pdf.text(`Prepared for ${businessName}`, margin, 40);

    // Content - split into lines
    pdf.setFontSize(10);
    const lines = pdf.splitTextToSize(doc.content, contentWidth);
    let y = 55;

    for (const line of lines) {
      if (y > 275) {
        pdf.addPage();
        y = 25;
      }
      pdf.text(line, margin, y);
      y += 5;
    }
  });

  return pdf.output("arraybuffer");
}
