import type { Metadata } from "next";
import { RubberStampCTA } from "@/components/RubberStampCTA";

export const metadata: Metadata = {
  title: "About DocketPack",
  description:
    "DocketPack generates every compliance document your UK business needs. Built because small business owners deserve simple, affordable compliance.",
};

export default function AboutPage() {
  return (
    <section className="bg-cotton py-16 md:py-20">
      <div className="mx-auto max-w-[800px] px-6 md:px-12">
        <h1 className="font-heading text-4xl text-walnut md:text-5xl">
          About DocketPack
        </h1>

        <div className="mt-8 space-y-6 font-body text-base font-light text-graphite leading-relaxed">
          <p>
            Running a small business in the UK means complying with dozens of
            regulations enforced by half a dozen different authorities. Environmental
            Health, the HSE, the Fire Service, the Licensing Authority, the Home Office,
            the ICO — each expects you to have specific documents in place.
          </p>
          <p>
            Most business owners know they need &ldquo;paperwork&rdquo; but don&apos;t know
            exactly which documents, what they should contain, or which laws
            they need to reference. So they Google templates, download generic PDFs,
            and hope for the best.
          </p>
          <p>
            DocketPack changes that. We generate every document your business needs,
            customised with your specific details — your business name, address,
            employee count, and operational specifics woven throughout. Each document
            references the correct UK legislation it satisfies.
          </p>
          <p>
            We started with restaurants because they face the most complex web of
            regulations — 52 documents across 8 categories. Salons, gyms, and
            construction are coming next.
          </p>
        </div>

        <div className="mt-12 border-t-2 border-dashed border-fold pt-8">
          <h2 className="font-heading text-2xl text-walnut">
            What DocketPack is not
          </h2>
          <div className="mt-4 space-y-4 font-body text-base font-light text-graphite leading-relaxed">
            <p>
              DocketPack is not legal advice. Our documents are generated by AI and
              reference current UK legislation, but they should be reviewed by a
              qualified professional before you rely on them for regulatory compliance.
            </p>
            <p>
              We provide the documents — you provide the professional review.
              Together, that&apos;s a fraction of the cost of having a solicitor draft
              everything from scratch.
            </p>
          </div>
        </div>

        <div className="mt-12">
          <RubberStampCTA href="/generate/" size="large">
            Generate Your Documents
          </RubberStampCTA>
        </div>
      </div>
    </section>
  );
}
