import type { Metadata } from "next";
import Link from "next/link";
import { RubberStampCTA } from "@/components/RubberStampCTA";

export const metadata: Metadata = {
  title: "Pricing — Restaurant Document Packs",
  description:
    "Restaurant compliance document packs from $79. Individual documents $9 each. Federal and state documents customised to your business, legally referenced, ready in minutes.",
};

const tiers = [
  {
    name: "Individual Document",
    price: "$9",
    period: "per document",
    description: "Generate a single document customised to your US business.",
    features: [
      "Any one federal or state document",
      "Customised with your business details",
      "Correct federal/state legal references",
      "PDF download",
      "Unlimited regenerations for 30 days",
    ],
    cta: "Choose Your Document",
    href: "/restaurant/",
    featured: false,
  },
  {
    name: "Complete Restaurant Pack",
    price: "$79",
    period: "one-time",
    description: "Every federal + state document your restaurant needs.",
    features: [
      "All federal compliance documents",
      "State-specific documents for your state",
      "Customised with your business details",
      "Correct federal & state legal references",
      "Single combined PDF",
      "Individual document PDFs",
      "Unlimited regenerations for 90 days",
    ],
    cta: "Generate Your Pack",
    href: "/generate/",
    featured: true,
  },
];

export default function PricingPage() {
  return (
    <>
      <section className="bg-cotton py-16 md:py-20">
        <div className="mx-auto max-w-[1120px] px-6 md:px-12">
          <h1 className="font-heading text-4xl text-walnut md:text-5xl">
            Pricing
          </h1>
          <p className="mt-4 max-w-xl font-body text-base font-light text-graphite">
            One price. No subscriptions. No hidden fees.
            Your documents are yours to keep.
          </p>

          <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-2">
            {tiers.map((tier) => (
              <div
                key={tier.name}
                className={`border p-8 ${
                  tier.featured
                    ? "border-2 border-burgundy bg-manila"
                    : "border-fold bg-manila/40"
                }`}
              >
                {tier.featured && (
                  <span className="mb-4 inline-block bg-burgundy px-3 py-1 font-mono text-[10px] font-bold tracking-wider text-cotton uppercase">
                    Best Value
                  </span>
                )}
                <h2 className="font-heading text-2xl text-walnut">
                  {tier.name}
                </h2>
                <div className="mt-4 flex items-baseline gap-2">
                  <span className="font-mono text-4xl font-bold text-burgundy">
                    {tier.price}
                  </span>
                  <span className="font-body text-sm text-graphite">
                    {tier.period}
                  </span>
                </div>
                <p className="mt-3 font-body text-sm font-light text-graphite">
                  {tier.description}
                </p>
                <ul className="mt-6 space-y-3">
                  {tier.features.map((feature) => (
                    <li
                      key={feature}
                      className="flex gap-3 font-body text-sm text-walnut"
                    >
                      <span className="mt-1 h-3 w-3 flex-shrink-0 border border-fold bg-cotton" />
                      {feature}
                    </li>
                  ))}
                </ul>
                <div className="mt-8">
                  <RubberStampCTA href={tier.href} size="large">
                    {tier.cta}
                  </RubberStampCTA>
                </div>
              </div>
            ))}
          </div>

          {/* UK pricing link */}
          <div className="mt-8 text-center">
            <p className="font-body text-sm text-graphite">
              UK business?{" "}
              <Link href="/uk/pricing/" className="text-burgundy underline underline-offset-4 hover:text-walnut">
                View UK pricing (£49/£9) &rarr;
              </Link>
            </p>
          </div>
        </div>
      </section>

      <section className="border-t-2 border-dashed border-fold bg-cotton py-12 md:py-16">
        <div className="mx-auto max-w-[1120px] px-6 md:px-12">
          <h2 className="font-heading text-2xl text-walnut">
            Frequently asked questions
          </h2>
          <div className="mt-8 grid grid-cols-1 gap-8 md:grid-cols-2">
            {[
              {
                q: "Are these documents legally valid?",
                a: "Each document references the specific federal or state laws it satisfies. They are generated by AI and should be reviewed by your attorney or compliance advisor before relying on them for regulatory purposes.",
              },
              {
                q: "Can I edit the documents after generation?",
                a: "Yes. You receive the documents as PDF files which you can print and use. The content is also provided in a format you can copy into your own templates.",
              },
              {
                q: "Do I get federal AND state documents?",
                a: "Yes. The complete pack includes all federal requirements (OSHA, FDA, EEOC, IRS, etc.) plus state-specific documents for your state covering minimum wage, food handler certs, liquor licensing, and more.",
              },
              {
                q: "Which states are currently supported?",
                a: "We currently have state-specific documents for California, Texas, Florida, and New York. Federal documents apply to all 50 states. More states are being added regularly.",
              },
            ].map((item) => (
              <div key={item.q}>
                <h3 className="font-body text-base font-medium text-walnut">
                  {item.q}
                </h3>
                <p className="mt-2 font-body text-sm font-light text-graphite leading-relaxed">
                  {item.a}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
