import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "DocketPack terms of service. Terms governing use of our document generation service.",
};

export default function TermsPage() {
  return (
    <section className="bg-cotton py-16 md:py-20">
      <div className="mx-auto max-w-[800px] px-6 md:px-12">
        <h1 className="font-heading text-4xl text-walnut">Terms of Service</h1>
        <p className="mt-4 font-mono text-xs text-graphite">Last updated: April 2026</p>

        <div className="mt-8 space-y-8 font-body text-sm font-light text-graphite leading-relaxed">
          <div>
            <h2 className="font-heading text-xl text-walnut">Service description</h2>
            <p className="mt-3">
              DocketPack provides AI-generated business compliance documents for UK businesses.
              Documents are generated based on information you provide and reference current
              UK legislation at the time of generation.
            </p>
          </div>

          <div>
            <h2 className="font-heading text-xl text-walnut">Important disclaimer</h2>
            <p className="mt-3">
              DocketPack does not provide legal advice. Documents generated by our service are
              created using artificial intelligence and, while they reference current UK legislation,
              they should be reviewed by a qualified solicitor, compliance advisor, or relevant
              professional before being relied upon for regulatory compliance purposes.
            </p>
            <p className="mt-3">
              We do not guarantee that documents will satisfy specific regulatory inspections
              or audits. Compliance is ultimately your responsibility as the business owner.
            </p>
          </div>

          <div>
            <h2 className="font-heading text-xl text-walnut">Payment and access</h2>
            <ul className="mt-3 space-y-2 list-disc list-inside">
              <li>Individual documents: £9 per document, with regeneration access for 30 days</li>
              <li>Complete restaurant pack: £49 one-time, with regeneration access for 90 days</li>
              <li>Payments are processed securely by Stripe</li>
              <li>All sales are final — documents are digital goods delivered immediately</li>
            </ul>
          </div>

          <div>
            <h2 className="font-heading text-xl text-walnut">Intellectual property</h2>
            <p className="mt-3">
              Documents generated for you are yours to use, modify, and distribute within
              your business. You may not resell generated documents or use them to create
              a competing service.
            </p>
          </div>

          <div>
            <h2 className="font-heading text-xl text-walnut">Limitation of liability</h2>
            <p className="mt-3">
              To the maximum extent permitted by law, DocketPack and its operators shall not
              be liable for any indirect, incidental, or consequential damages arising from
              use of generated documents, including but not limited to regulatory fines,
              business losses, or legal costs.
            </p>
          </div>

          <div>
            <h2 className="font-heading text-xl text-walnut">Governing law</h2>
            <p className="mt-3">
              These terms are governed by the laws of England and Wales.
              Any disputes shall be subject to the exclusive jurisdiction of
              the courts of England and Wales.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
