import type { Metadata } from "next";
import { RubberStampCTA } from "@/components/RubberStampCTA";

export const metadata: Metadata = {
  title: "UK Pricing — Restaurant Document Packs",
  description:
    "UK restaurant compliance document packs from £49. Individual documents £9 each. All documents customised to your business, legally referenced, ready in minutes.",
};

const tiers = [
  {
    name: "Individual Document",
    price: "£9",
    period: "per document",
    description: "Generate a single document customised to your UK business.",
    features: [
      "Any one UK restaurant document",
      "Customised with your business details",
      "Correct UK legal references",
      "PDF download",
      "Unlimited regenerations for 30 days",
    ],
    cta: "Choose Your Document",
    href: "/uk/restaurant/",
    featured: false,
  },
  {
    name: "Complete UK Restaurant Pack",
    price: "£49",
    period: "one-time",
    description: "Every UK document your restaurant needs in one pack.",
    features: [
      "All UK restaurant documents",
      "8 categories covered",
      "Customised with your business details",
      "Correct UK legal references",
      "Single combined PDF",
      "Individual document PDFs",
      "Unlimited regenerations for 90 days",
    ],
    cta: "Generate Your Pack",
    href: "/uk/generate/",
    featured: true,
  },
];

export default function UKPricingPage() {
  return (
    <>
      <section className="bg-cotton py-16 md:py-20">
        <div className="mx-auto max-w-[1120px] px-6 md:px-12">
          <div className="flex items-center gap-3 mb-4">
            <span className="inline-block border-2 border-walnut px-3 py-1 font-mono text-xs font-bold tracking-wider text-walnut uppercase">
              UK
            </span>
          </div>
          <h1 className="font-heading text-4xl text-walnut md:text-5xl">
            UK Pricing
          </h1>
          <p className="mt-4 max-w-xl font-body text-base font-light text-graphite">
            One price. No subscriptions. No hidden fees.
            Your documents are yours to keep. All prices in GBP.
          </p>

          <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-2">
            {tiers.map((tier) => (
              <div
                key={tier.name}
                className={`border p-8 ${
                  tier.featured
                    ? "border-2 border-burgundy bg-manila"
                    : "border-fold bg-manila/40"
                }`}
              >
                {tier.featured && (
                  <span className="mb-4 inline-block bg-burgundy px-3 py-1 font-mono text-[10px] font-bold tracking-wider text-cotton uppercase">
                    Best Value
                  </span>
                )}
                <h2 className="font-heading text-2xl text-walnut">
                  {tier.name}
                </h2>
                <div className="mt-4 flex items-baseline gap-2">
                  <span className="font-mono text-4xl font-bold text-burgundy">
                    {tier.price}
                  </span>
                  <span className="font-body text-sm text-graphite">
                    {tier.period}
                  </span>
                </div>
                <p className="mt-3 font-body text-sm font-light text-graphite">
                  {tier.description}
                </p>
                <ul className="mt-6 space-y-3">
                  {tier.features.map((feature) => (
                    <li key={feature} className="flex gap-3 font-body text-sm text-walnut">
                      <span className="mt-1 h-3 w-3 flex-shrink-0 border border-fold bg-cotton" />
                      {feature}
                    </li>
                  ))}
                </ul>
                <div className="mt-8">
                  <RubberStampCTA href={tier.href} size="large">
                    {tier.cta}
                  </RubberStampCTA>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="border-t-2 border-dashed border-fold bg-cotton py-12 md:py-16">
        <div className="mx-auto max-w-[1120px] px-6 md:px-12">
          <h2 className="font-heading text-2xl text-walnut">
            Frequently asked questions
          </h2>
          <div className="mt-8 grid grid-cols-1 gap-8 md:grid-cols-2">
            {[
              {
                q: "Are these documents legally valid?",
                a: "Each document references the specific UK legislation it satisfies. They are generated by AI and should be reviewed by your solicitor or compliance advisor before relying on them for regulatory purposes.",
              },
              {
                q: "Can I edit the documents after generation?",
                a: "Yes. You receive the documents as PDF files which you can print and use. The content is also provided in a format you can copy into your own templates.",
              },
              {
                q: "How long does generation take?",
                a: "A single document takes about 30 seconds. The full document pack takes 3-5 minutes. You'll see progress as each document is generated.",
              },
              {
                q: "Do I get updates when regulations change?",
                a: "Your generated documents reflect current UK legislation at the time of generation. If regulations change, you can regenerate within your access period.",
              },
            ].map((item) => (
              <div key={item.q}>
                <h3 className="font-body text-base font-medium text-walnut">
                  {item.q}
                </h3>
                <p className="mt-2 font-body text-sm font-light text-graphite leading-relaxed">
                  {item.a}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
